### PR TITLE
changing Probes to use MYSQL_USER and MYSQL_PASSWORD

### PR DESCRIPTION
**Pull request by christianhuth**
#14

### CODE REVIEW

**Review by rubenhak — CHANGES_REQUESTED** [review]
Could you check lines 55-63? **MYSQL_USER** and **MYSQL_PASSWORD** variables are optional  and are set only if **.Values.mysql.db_user** is set and is not equal to **"root"**.

**Comment by christianhuth** [comment]
@rubenhak: sorry haven't been working on kubernetes lately. I added an if-statement which takes the defined mysql.db_user in context.

**Comment by christianhuth** [comment]
@rubenhak: do you still need something for this to be merged?

**Comment by rubenhak** [comment]
@christianknell, give me a couple of days to experiment with this change to make sure that it will work with upgrades, etc. 

Btw, this will be not important once we get mysql deployed using bitnami charts, right?

**Comment by christianhuth** [comment]
@rubenhak: Yes that's true. The bitnami charts come with probes already included.

**Pull request merged**
