### PR TITLE
Allow to use different StorageClass

### LINKED ISSUE #4: unable to change the storage class of mysql
There is no way in current release to change the storage class of the PVC created for the Mysql include inside of kubevious.
If no storageclass default is defined in a K8S the deployment failed as the PVC stays in pending mode
image

### PR DESCRIPTION
**Pull request by obeyler**
This PR will fix #4

### CODE REVIEW

**Comment by rubenhak** [comment]
@obeyler, thanks for the fix. I have some comments.

**Review by rubenhak — CHANGES_REQUESTED** [review]
Lets don't update the version number in the chart. Versions are automatically bumped up in CI/CD pipeline

**Review by vladh91 — APPROVED** [review]

**Comment by obeyler** [comment]
@rubenhak I  change the Chart version back as you requested

**Comment by rubenhak** [comment]
@obeyler, looks great. Thanks for submitting the issue and the solution!

**Pull request merged**
